# Pisidian Antioch

## Background

Miniature Rome - founded on 7 hills

Re-founded by Caesar Augustus after he shrunk the army to 28 legions, with a resulting increase in veterans. He gave land grands in Pisidian Antioch to retired soldiers.

Herod and Caesar shared the same worldview, but Herod was hemmed in by the territory of Israel 

## Geography

Founded 3C BC to protect major roads. Roman roads were critical for rapid movement of troops. In peacetime, roads provided rapid travel.

6BC Via Sebaste built between Pisidian Antioch and Perga (port city on the coast).

Paul likely took the Via Sebaste north at the beginning of first missionary journey, and travelled overland on the way back 


## History

City founded by Antiochus I (Seulicid)

190 BC Battle of Magnasia

189BC Treaty of Apamea

131 BC Attelid 

31BC Battle of Actium. Mark Anthony defeated by Octavian (soon to become Cesaer Augustus). 

25 BC Caesar refounded Antioch towards Pisidian as a Roman colony


## Social mobility

Roman economy was founded upon slavery. Sparticus lead a slave revolt in XXX.  Emporer realized that social mobility would be necessary to give some hope to slaves and prevent another slave revolt. Manumission was the process of freeing a slave, in which the slave would become a client of the former owner. Urban slaves were better off than the rural poor (freeman) because of the protection of the patron.  This gave more social mobility to Roman society compared with Greek society, where once a slave you were always a slave.

Eary church considered all social classes equal in standing before God, which threatened the established social order of Rome. 

## Eastern Frontier

Eastern frontier was a treat to Rome, both from Jewis uprising in Israel and the Parthians. Herod was instrumental in defending eastern frontier. 

40BC Parthians had installed Antigonis. Herod fled to Rome to ask for help.  Herodian built as a memorial. Antonian fortress - Herod was friends with Mark Anthony. When Cesaer Agustus defeated Mark Anthony in 30BC Herod went over to Augustus.

## Revelations

Written to the persecuted church - Written in code so that the Romans wouldn't decipher. 

## Hemeneutics

Proverbs =/= promises

## Bible

Acts 13:14 Paul travels to P antioch

Acts 14:21  Preached gospel and returned to Antioch

Acts 16:16

Second missionary journey
