# Clark Millikan

Clark Milliken Wife was 1) Nancy Adams and 2) Lydia Hinshaw

Clark's Children

- Lewis Elwood Millikan (1855-1949)
    - Arza Millikan (1883-1964)
- Alice Millikan Cox (1894- ) Married Owen Dudley Cox
    - Carrie Cox Bell
    - Stella (died young)
- Sister
- Sister
- Sister


Clark Millikan was considered a deserter of the Confederate, so he couldn't return to North Carolina. He sent for his wife, Lydia Hinskaw Millikan, to join him. She travelled by wagon train from Randolph County, NC to Hamilton County, IN, which was a 3 month journey which had to be made in summertime.  She had difficulty finding a wagon train to take her and her family because the family did not have an adult male to help with the work.  The wagon train members agree to allow her son Elwood (age 10) to work in tending the animals. Elwood walked from North Carolina to Indiana. Somewhere in mountains. Alice's grandmother was a baby ?1 year. Was born in 1864 (this was 1865). She got very sick, and women in wagon train agreed that she was dying. Wagon train was considerate. Came to a little village. We will camp here overnight. Men will use the day to repair harnesses, etc overnight. There was a graveyard in the little village.  Young and old tended to die on the way.  Tended to make an umarked grave along the way. Grandmother didn't die that night.  Aunt angeline could probably drive that team.


Clark spent most of his life clearing the farm land

[Chasing Ancestors Blog](https://chasingancestors.com/2016/10/25/the-growth-of-the-farm/amp/)

Clark Millikan 101 when he died. 2 months shy of 102nd birthday. Alice Cox taking care of aunt Angeline and Clark. (Mom's great grandfather). Alice Cox was putting away Clark's winter underwear without mending it - a sign the time. Alice Cox (had to admit sheepishly that he wouldn’t need them that year, but the next winter he did need them.

Clark was older and not longer farming but grandson Arza was farming. Was 101 and was digging outlet of tile ditch.  Probably doing it himself because it had to be done precisely. Got hot and perspired and cooled off too rapidly and got pneumonia and he died.  Celebrated 60th wedding anniversary. Clark died then a few weeks later, Angeline died. Then Alice Millikan Cox dies soon thereafter.  People may have more controll over it than thought.


Millikan was disciplined by Marlboro Friends meeting because he had married (?) "out of fellowship" to ?Nancy Adams


[Geneological society Hamilty County](http://www.hcgsohio.org/cpage.php?pt=147)
