# Nancy Angeline Millikan (1852-1926)

She was the eldest daughter of Clark Millikan (1824-1926). Her mother, Clark Millikan's first wife, Nancy Adams, died 10 days after Angeline was born.  She had no children

[Crack Shot Aunt Angeline](https://chasingancestors.com/2017/08/01/aunt-angie-crack-shot/)

Squirrel hunter…. Clark Millikan - First wife to gave birth to Angeline and died 10 days later.  Older child (Carrie did;t have much respect for her).  Aunts took care of her.  Clark remarried Lydia Hinshaw - Mom's great grandmother.  Angeline typical spinster aunt. Never married.  Severe mannish looking. Hair tight in a bun. Liked to do was take rifle, sit on a stump, and shoot squirrels. 

After John William Bell died, his brother Uncle Chester visited for some reason.  Man came to door and could see woods in the back.  Wanted to go squirrel hunting in the woods. Sob story - wife was ill with cancer, and not expected to live.  Must eat, had no appetitie. If she could have some squirrel.  Still answer was no.  No hunting allowed in the woods. Uncle Chester:  "You can hunt in my woods." He was upset that Carrie had denied man the dying wish of his wife.

**Who was Uncle Chester??**
