---
title: "Alice Bell"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Birth

Alice Bell was born July 30, 1923 to Carrie Cox Bell and John William Bell on a farm in Boone County, Indiana adjacent to her grandfather Bell's farm.  Subsequent to the death of her great-grandfather on her mother's side, Clark Millikan, her family moved to a farm in Hamilton County outside Sheridan, Indiana.  She grew up with John Dudley Bell and half-sisters Dora Katherine (Walker) and Rosemary (Hockett).

## Move to Hamilton County

Carrie's grandfather Clark Millikan had owned a farm in Hamilton County, Indiana since 1865.  After Clark's death in 1926, an 80-acre parcel was offered for sale.  John and Carrie Bell sold the farm in Boone County and moved to Clark's farm in 1929. John and Carrie Bell took out a mortgage to purchase the farm in Hamilton County.  Over the years, it bothered Carrie quite severely to carry a debt, even for the farm.  They subsequently bought an additional 17 acre triangle, to make a total of 97 acres.



## Clark Millikan

In 1862 the Confederate Congress did enact a five-hundred-dollar exemption fee, which many Quakers paid, but some did not. Payment of this fee excused a person from military service. In 1864 the Quakers also received approval to perform certain types of work as a substitute for military service. One type of service was working at the saltworks in Wilmington. Another was laboring in the leather tanning and shoe industries, which Quakers owned. From [NCPedia](https://www.ncpedia.org/quakers-and-their-war-resistance)

After the war, Abraham Lincoln resetteled Confererate deserters.

Traded farms with his cousin, who owned a frma in Hamilton County, Indiana.  The cousin's wife had recently died, leaving him with 2 small children.  The cousin was eager to return to North Carolina where he had family who could him him raise his children.  Clark Millikan's farm in Randolph County, NC was a developed, working farm, and the 80 acres in Hamilton County, IN contained only 8 acres of cleared land.  Clark's cousin offered 400 dollars to make up the difference in value of the two farms.

**Who was Bales?**

Clark Millikan was considered a deserter of the Confederate, so he couldn't return to North Carolina. He sent for his wife, Lydia Hinskaw Millikan, to join him. She travelled by wagon train from Randolph County, NC to Hamilton County, IN, which was a 3 month journey which had to be made in summertime.  She had difficulty finding a wagon train to take her and her family because the family did not have an adult male to help with the work.  The wagon train members agree to allow her son Elwood (age 10) to work in tending the animals. Elwood walked from North Carolina to Indiana. Somewhere in mountains. Alice's grandmother was a baby ?1 year. Was born in 1864 (this was 1865). She got very sick, and women in wagon train agreed that she was dying. Wagon train was considerate. Came to a little village. We will camp here overnight. Men will use the day to repair harnesses, etc overnight. There was a graveyard in the little village.  Young and old tended to die on the way.  Tended to make an umarked grave along the way. Grandmother didn't die that night.  Aunt angeline could probably drive that team. 

Native Americans lived off acorns, which they referred to as a grain that grows on tree.

Clark Millikan 101 when he died. 2 months shy of 102nd birthday. Alice Cox taking care of aunt Angeline and Clark. (Mom's great grandfather). Alice Cox was putting away Clark's winter underwear without mending it - a sign the time. Alice Cox (had to admit sheepishly that he wouldn’t need them that year, but the next winter he did need them.

Clark was older and not longer farming but grandson Arza was farming. Was 101 and was digging outlet of tile ditch.  Probably doing it himself because it had to be done precisely. Got hot and perspired and cooled off too rapidly and got pneumonia and he died.  Celebrated 60th wedding anniversary. Clark died then a few weeks later, Angeline died. Then Alice Millikan Cox dies soon thereafter.  People may have more controll over it than thought.

At that point, family bought 80 acres.  Mom born and first five year in boone county.  Adjacent to Grandfather Bell. Then mooved to Hamilton County. Traded 209 acres in NC for 80 acres of trees in Indiana and money in addition  Spent rest of life turning it into 

Carrie gave John D and Alice 80 acres of land each in 1963.  Mom got 80 acres of Clark's land.  John was living on the other 80 acres, so John got the 80 acres he was living on it.

At time of carrie's death, there was additional land. Mom elected to let John D buy all the rest (from the estate).  Carrie had bought Stewart place, and place Emmil Hammock had farmed. She also bought were new house was, 35 or 50 acres.

Marilynn - two trusts - John D Bell trust - included his 80 + 17 + Stewart farm.  Other one is the Marilynn Bell trust with the land of Highway 38 with new house.

Carrie - began to ask friend. 

Alice Cox - DID she have PCKD? Died of renal failure… Died at 68.   

Marilyn called Mom to come to Sheridan because time was near.  Mom saw how she ate a Thanksgiving, and knew end was not near.  Died at least two years later. She subsequently fell… bent dishwasher

 door Marilyn was calling daily.  Went to nursing home…. 

Farm Life in 1930s


Also bought 17 acres triangle.  Had been a farmhouse there - there were day lillies there in 1939.  When he(?) died, had 97 acres.

Adjacent 20 acres available which John and Carrie = 117.  After John's death during WWII. When John D had to maintain a farm deferrment, Carrie bought additional land..


Grandmother kept chickens and sold the eggs. She was permitted to keep the proceeds and manage it on her own.

Farm produced hay, and this would need to be harvested and brought into the hay mow (loft).  
John (William?) Bell had one of the first international harvester apparatus in the area


Innovation was a hay rake which could be used with a tractor

Mom was assigned to lead the horses, which were used to pull the load of hay up into the hay loft.

John gave up milking due to (when? - John william or John D)

Graound feed wheat, oats, ?corn brought to elevator and they add supplements.

Millking 8 cows - John Bell wanted to milk 12 hours apart - had about 8 cows.  Each had its own stall, and got fed when they were 

Women helped in house and with chicken.  

Carrie raised laying hens and fryers.  Gathering eggs is dangerous - as hens. Carrie would grab the head and push it.  Mom would use work gloves to gather eggs.  

Chicken coop was innovative with plans from Perdue.  Two rooms 20x40 feet.  No power tools. Saw lumber by hand. Specifications from Perdue.  Poured cement foundation. Burgler alarm - run on batteries (no electricity on the farm). He would set the alarm in the kitchen when he retired.  In the morning would need to disable the alarm.

Neighbor who came to help with bringing in hay - set of alarm and part broke off and hit him in the head.

A lot of work - but he did it efficiently.  Had wanted to go to Perdue and be an engineer. But that wasn't an option.  

Tim - toys from Paul Bruce - make out of metal with tabs…  Fixing things at home - complete with explanations…


Carrie attended nursing school at prostatent deaconess nursing school indianapolis. Later merged with ???

Private duty nursing Dr Scamahorn -

Dr Link praccticing when she was in training. He did her thyroid surgery.

Carrie took John Wm to a diagnostician when he was later found to have pancreatic cancer.

Mary Rawlilngs was John Wm's first husband.

Carrie and John William married in indianapolis at Prostatant deconess church by a pastor she knew from the hospital.

Mrs Randolph took the photo - Widow who supported herself and had a photography studio in Sheridan. In photo, John D and Alice were prob 9 and 10.  Mary born in 14 and Rosemary in 1915.  

GF Milikan - liked trees. Planted flowering Dogwood. Planted patch of poplar on East side. Planted persimmons around house. Planted apples from the 4th orchard. 

Cut wood for fire in kitchen. Winter wood - slow…
	Summer wood -> ash - would burn and die down
	
------



From May 2022

Clark was an old man in dark clothes who always sat by the window in the living room.

Clark died in XXX

Took over family farm in 1929.

Log cabin built by Clark Milliken. Used log cabin whhen they built the barn.

When the barn was demolished, worker asked to recycle the logs from the original log cabin

Clark acquired the farm in 1865, Abraham Lincoln gave him a free train ride to any place he wanted to go in the Union.  He chose Boone County, Indiana, where a cousin owned 80 acres of farmland.

Towards the end of the Civil War, it became

Cousin in Indiana's wife died, leaaving him with two small children. Cousin wanted to go abck to North Carolina.

Clark had an estabished farm in NC, he got additionall money.

Got 80 acres in Hamilton County, of which only 8 acres had been cleared for farming.

Started with log cabin, then moved log cabin and built barn around it.

House built - Originally square, two floor house. Four rooms down and two rooms up. Later added 'lean-to' addition of two additonal rooms: Kitchen and dining room. Wood-fired stove in kitchen.  Coal-burning "base-burner" in living room. Window of mica to allow inspection of the flame (and know when to add more coal). 

Wood range and possibly coal

Breakfast - cooked cereal, bacon, 

Farm with animals as well as crops

Purchased farm in 1929 available with mortgage - bothered Carrie a lot.  Additional 17 acre triangle purchased as well.

Arza Millikan 

Chores as a teenager:  Help out with household work. John D helped outside. John D was mother's favorite child (was a boy).

Liked to read - Mother didn't think much as an activity.  Library in Sheridan.  Books around the house. Left by other members of the family. 

School bus to school in Sheridan.

Father died when just graduated from high school - Wanted to change subject.

Carrie's big dream (for Alice) was to do to Earlham College.  Carrie told how much she would pay and the rest Alice had to do. Worked in dining room and worked in laundry.  In laundry, took wet sheets one person on each end by corner and give a good shake. Ironed on the mangle.  Usually didn't have student labor in the laundry - fortunate to have that job.  Limited budget at Earlham - worked hard, got good grades and graduated.

University of Wisconsin Masters of Arts in English on scholarship. Stayed on one year to teach. Waiting on tables in the dining hall. 

Real job at Heidelburg College in Tiffin,OH. Teaching English for 2 years.  Decided she wanted more education to be "fully qualified" teach with a PhD.


UofM for PhD. Working as a house mother in a dorm.  Lorna lived in house - told Mom about an uncle she had.  Melvin was anxious to get back to school.  Alice "was the victim" 

Moved to Iowa - Melvin ?had a job at Iowa. Cedar Falls. Tim was born then. Lots of work

Back to Minneapolis - Melvin started teaching.  

Resumed education at University - Resumed education 1967 


PhD in English - 1984.  Thesis - Professor's House by Willa Cather. 

What brought joy during time in Minneapolis?  Campus of the UofM.  Took streetcar to Lake Harriet and study. 

Meet Jim Meyer in the 1990' at an Ederhostel at the airport near 4 Corners


Lived in Davis for a few years. 

Moved back to Minneapolis to Becketwood,

Served on Finance Committee, Investment Committee, Food Committee, Chair of Investment Committee for 9 years. Kept a garden. Behaved. 




Owen Dudley Cox - From North Carolina -




