---
output:
  pdf_document: default
  html_document: default
---
# Sardis
Saturday Sept 18th morning

## Gospel of John

- Written to Asia

## Vineyards

Jn


Ancient vineyards run along the ground.  In contact with ground, grapes can become contaminated with fungus (grape smut?) which stunts their growth

Modern vineyards raise the vines off the ground on wires.

Vinedresser in ancient times if they found contaminated grapes, wound life up vines on a rock on on a forked stick in order to allow the sun to dry off the grapes and combat grape fungus.


Every branch that bears fruit the vinedresser prunes, that it will bear more fruit.

Pruning cuts off leaves 

- Allows sun to get to other leaves
- Permits directing nutrients



=> We need to trim the good things in our lives to make energy for the great things.

Requires being clear on who you are and what you are uniquely called (and gifted) to do

"Good to Great" - Enemy of great is good

Brad Gray - As a candidate for a pastoral job - re-wrote the job description and handed it back go searach committee.

Look at how many times Jesus disppointed those around him (people he didn't heal). "That is why I have been sent"

Imperative : __remain in me__

## What are the fruit

### Good works

You will know (false prophets) by their fruit - Can bramble bear good fruit?

### Fruits of the Spirit

Character as evidenced by good deeds





## John 15-17

Where do the events in these chapters take place?

John 14: Let us leave (Upper Room)

John 18 - Jesus left -> corssed the Kidron Valley
Perhaps they left the Eastern Gate after leaving the temple, which would lead to the garden (also referred to as Geshsemene).

### Did John 15-17 take place in the Temple

Temple was left unlocked during passover (so that the Messiah wouldn't be locked out of the temple)

Jesus was the new Moses

- 
